//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administration()
        {
            this.Signals = new HashSet<Signal>();
            this.Workplaces = new HashSet<Workplace>();
            this.LocalRoles = new HashSet<LocalRole>();
            this.Activities = new HashSet<Activity>();
            this.Batches = new HashSet<Batch>();
            this.AdministrationCertificates = new HashSet<AdministrationCertificate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Oid { get; set; }
        public Nullable<long> Number { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string Uic { get; set; }
        public bool IsClosed { get; set; }
        public string KindCode { get; set; }
        public bool IsPublicServiceProvider { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signal> Signals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workplace> Workplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalRole> LocalRoles { get; set; }
        public virtual AdministrationKind AdministrationKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdministrationCertificate> AdministrationCertificates { get; set; }
    }
}
