//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public System.DateTime TimeAccessed { get; set; }
        public string IPAddress { get; set; }
        public string URL { get; set; }
        public string Data { get; set; }
        public string Activity { get; set; }
        public Nullable<long> Duration { get; set; }
        public string UserName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string SessionID { get; set; }
        public string RequestMethod { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
