//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReguxEntities : DbContext
    {
        public ReguxEntities()
            : base("name=ReguxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Response> Responses { get; set; }
        public virtual DbSet<ServiceStep> ServiceSteps { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<PidType> PidTypes { get; set; }
        public virtual DbSet<Signal> Signals { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Administration> Administrations { get; set; }
        public virtual DbSet<UserLocalRole> UserLocalRoles { get; set; }
        public virtual DbSet<LocalRole> LocalRoles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
    }
}
