//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int ServiceId { get; set; }
        public string Argument { get; set; }
        public string CallContext { get; set; }
        public System.DateTime DraftDateTime { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> DeleteDateTime { get; set; }
        public string Error { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Response Response { get; set; }
        public virtual Service Service { get; set; }
    }
}
