//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStep
    {
        public int ParentId { get; set; }
        public byte StepNumber { get; set; }
        public int ChildId { get; set; }
    
        public virtual Service Children { get; set; }
        public virtual Service Parent { get; set; }
    }
}
