//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Requests = new HashSet<Request>();
            this.ChildInServiceSteps = new HashSet<ServiceStep>();
            this.ParentInServiceSteps = new HashSet<ServiceStep>();
            this.Signals = new HashSet<Signal>();
        }
    
        public int Id { get; set; }
        public string RegiXOperation { get; set; }
        public int AdministrationId { get; set; }
        public string Name { get; set; }
        public string LegalBasis { get; set; }
        public string Category { get; set; }
        public string RegimeType { get; set; }
        public bool IsEu { get; set; }
        public bool IsInternal { get; set; }
        public bool IsRegime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceStep> ChildInServiceSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceStep> ParentInServiceSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signal> Signals { get; set; }
        public virtual Administration Administration { get; set; }
    }
}
