//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.Signals = new HashSet<Signal>();
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LegalBasis { get; set; }
        public bool IsEu { get; set; }
        public bool IsInternal { get; set; }
        public bool IsRegime { get; set; }
        public Nullable<long> Number { get; set; }
        public string SectionCode { get; set; }
        public string Subsection { get; set; }
        public string RegimeName { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> IisdaUpdateDateTime { get; set; }
        public string IisdaUpdateResult { get; set; }
        public Nullable<int> RegiXReportId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signal> Signals { get; set; }
        public virtual ServiceSection ServiceSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual RegiXReport RegiXReport { get; set; }
    }
}
