//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signal
    {
        public int Id { get; set; }
        public System.DateTime SubmitDateTime { get; set; }
        public System.DateTime IncidentDateTime { get; set; }
        public int ServiceId { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string SenderPidTypeCode { get; set; }
        public string SenderIdentifier { get; set; }
        public string SenderContact { get; set; }
        public string SenderNote { get; set; }
        public int AdministrationId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual PidType PidType { get; set; }
        public virtual Service Service { get; set; }
        public virtual Administration Administration { get; set; }
    }
}
