//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kontrax.Regux.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLocalRole
    {
        public string UserId { get; set; }
        public int AdministrationId { get; set; }
        public string LocalRoleCode { get; set; }
    
        public virtual Administration Administration { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual LocalRole LocalRole { get; set; }
    }
}
